name: Node.js CI

on:
  push:
    branches: [ main, test, dev ]
  pull_request:
    branches: [ main, test, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/my-angular-app/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend/my-angular-app

    - name: Build
      run: npm run build --if-present
      working-directory: ./frontend/my-angular-app

    - name: Check for test script
      id: check_test
      run: |
        if [ -f ./frontend/my-angular-app/package.json ] && grep -q '"test":' ./frontend/my-angular-app/package.json; then
          echo "Test script found, proceeding with tests."
          echo "::set-output name=should_run::true"
        else
          echo "No test script found, skipping tests."
          echo "::set-output name=should_run::false"
        fi
        
    - name: Run tests
      if: steps.check_test.outputs.should_run == 'true'
      run: npm test
      working-directory: ./frontend/my-angular-app
